name: Link-check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run linksafe
        uses: TechWiz-3/linksafe@main
        with: # comma seperated lists
          verbose: true
          whitelist_links: "https://learnopengl.com/In-Practice,https://www.intertech.com/Blog/xamarin-tutorial-part-1-create-a-blank-app/,https://semaphoreci.com/community/tutorials/,http://www.byperth.com/2018/04/25/guide-web-scraping-101-what-you-need-to-know-and-how-to-scrape-with-python-selenium-webdriver/,https://data-flair.training/blogs/advanced-python-project-detecting-fake-news/"
